# -*- coding: utf-8 -*-
"""
probe_piezo_p5_e31_inverse_2026-09-20.py

Paper 5 Option A synthetic inverse: recover e31 from the SC-vs-elastic
flexural gap on the homogeneous thickness-poled PZT-4 Kirchhoff ring,
holding c11_bar (i.e. the raw C11E/C12E/C13E/C33E stiffnesses) at their
known Duan Table 1 / Paper 4 BASE_KWARGS values. Same G0/G1/G2 discipline
as Paper 4's probe_piezo_p4_ff_open_circuit_2026-09-16.py and
probe_piezo_p4_sequential_e_e31_2026-09-16.py, cloned and re-pointed:
there is no host E here and no OC/SC split to invert (Phase 0 theorem,
PAPER5_DERIVATION.md Sec 4, LESSONS_LEARNED.md Sec 18.199/18.203: fully-
electroded open-circuit flexure coincides with short-circuit flexure for
every mechanical BC on this stacking, confirmed in 3-D FE job 2520476).
The one flexural observable is SC vs elastic (PiezoMonolithicOutOfPlane
Solver.coupled_bisect vs .elastic_bisect), not SC vs OC.

References: PAPER5_MONOLITHIC_PIEZO_ROADMAP.md Sec 6 (inverse protocol),
PAPER5_DERIVATION.md Sec 6 (stiffening sign, long-wave ~0.2% of e31 at
0.01% freq orientation estimate) and Sec 7 (claim A locked), LESSONS_
LEARNED.md Sec 18.199-18.203. Live operator:
plate_solver/piezo_monolithic.py PiezoMonolithicOutOfPlaneSolver
(elastic_bisect, coupled_bisect). Worker path:
plate_solver/workers.py _piezo_mono_coupled_ff_root_worker /
_piezo_mono_coupled_cc_root_worker (regression-gated below, not used for
every inner call -- the outer shooting loop is inherently serial, same
justification as probe_piezo_p4_sequential_e_e31_2026-09-16.py's own
"this probe stays single-process" note).

STANDING BANS (PAPER5_MONOLITHIC_PIEZO_ROADMAP.md Sec 12), respected here:
no SOLVER_VERSION bump; no OC frequency solver; no OC-vs-SC inverse; no
joint-fit of (c11_bar, e31) from one SC mode (c11_bar is FIXED at its
known value throughout -- only e31 is unknown); no Parashar/Mindlin/
in-plane.

MODEL: PiezoMonolithicOutOfPlaneSolver.coupled_bisect(lo, hi, n=0) is the
F-F n=0 short-circuit root of the 6x6 chi-cubic/Bessel determinant
(PAPER5_DERIVATION.md Sec 2). C11E, C12E, C13E, C33E, e33, X11, X33, rho,
geometry are all held at their known PZT-4/Duan values; e31 is the sole
unknown, inverted from a synthetic "measured" SC frequency generated by
the same operator at the true e31 (no injected noise for G0 -- pure
round-trip self-consistency, same as Paper 4's own G0 bar).

STRUCTURAL FACT FOUND THIS SESSION (not previously documented -- record
in LESSONS_LEARNED): _cubic_coeffs(omega) is built from e31_bar = e31 -
(C13E/C33E)*e33 through beta, gamma (each linear in e31_bar) and is odd
in e31_bar for the chi^3/chi^1 coefficients (a3, a1) and even for the
chi^2/chi^0 coefficients (a2, a0). Flipping e31_bar -> -e31_bar therefore
maps the cubic's root set {chi_i} -> {-chi_i} while leaving each lam_i
invariant (lam's numerator and denominator both flip sign together), and
leaves K_pref*chi = (4H/pi)*e31_bar*chi invariant termwise (K_pref flips,
chi flips, product invariant) -- so coupled_det's m_row and q_row blocks
are UNCHANGED and only phip_row flips sign as a whole block, an overall
row-scaling that does not change where det=0. Net: coupled_bisect(e31)
and coupled_bisect(twin) give BIT-IDENTICAL frequencies, where
    twin(e31) = 2*(C13E/C33E)*e33 - e31.
At E31_TRUE=4.1, twin = 13.800869565217392 -- numerically confirmed
below (not gated; documented as the reason the search bracket for e31
must avoid both e31_bar=0 (~8.9504, where the cubic degenerates from
cubic to quadratic) and the twin itself. This is the Paper-5-specific
analogue of Paper 4's own e31 reflection-twin caveat (Sec 18.175); do
not chase it (roadmap's own explicit instruction).

PRE-REGISTERED PASS/FAIL:
  G_worker (regression gate, not optional): worker-path scalar
     reconstruction _piezo_mono_coupled_ff_root_worker (and the C-C
     sibling) must match the in-process coupled_bisect / cc_coupled_
     bisect to <1e-9 relative at E31_TRUE, before any inversion result
     built on the in-process class is trusted (project standing rule:
     always regression-test through the worker path).
  G0 (inverse self-consistency, exact data, no injected noise): invert
     nature's own exact F-F n=0 SC frequency for e31 at fixed c11_bar
     (fixed C11E, C12E, C13E, C33E) via bisection on the physical
     branch e31 in [E31_LO, E31_HI] = [1.0, 8.0] (comfortably clear of
     the e31_bar=0 singular point ~8.9504 and the reflection twin
     ~13.80). PASS bar: rel_err < 1e-6 against E31_TRUE, same bar as
     Paper 4's own G0/G4.
  G1 (root quality / negative control): (a) genuine sign flip of
     G(e31) = omega_coupled(e31) - omega_target across [E31_LO, E31_HI];
     (b) a wrong-sign bracket [NEG_LO, NEG_HI] = [-8.0, -1.0] must show
     NO sign flip (the wrong-sign branch does not spuriously recover
     the target frequency); (c) e31=0.0 is a genuine singular limit of
     the chi-cubic (PAPER5_DERIVATION.md Sec 2 / _require_coupled_consts)
     and must raise ValueError, not silently return a frequency -- so
     "e31=0 must not recover the true value" holds by construction, not
     by accident.
  G2 (on-branch sensitivity, reported not gated): forward finite-
     difference domega/de31 at E31_TRUE; propagated relative e31
     uncertainty at 0.01% and 0.1% assumed frequency precision.
     Pre-registered expectation from PAPER5_DERIVATION.md Sec 6's
     long-wave estimate: ORDER 0.2% of e31_true at 0.01% freq (not a
     bar to tune to -- orientation only, an independent numeric
     confirmation of that closed-form estimate is itself a finding).
  G_reflection (bonus structural check, reported not gated): coupled_
     bisect(TWIN) reproduces coupled_bisect(E31_TRUE) to machine
     precision, confirming the reflection-symmetry finding above.
  Optional cheap: identical G0/G1/G2 recipe on C-C SC (cc_coupled_
     bisect) -- also splits vs elastic (Sec 18.201: +2.16%), same
     c11_bar-known / e31-unknown structure. NOT an OC-vs-SC inversion
     (there is no C-C OC solver here, same theorem as F-F).

SANDBOX cost model (this session, in-sandbox on the connected desktop,
dps=60/iters=45, matching TestPiezoMonoElastic/TestPiezoMonoCoupled's
own anchored precision -- "do not retune" applies to those test anchors,
not to this probe's own dps choice, but dps=60 was chosen deliberately
to match them rather than re-litigate precision): one coupled_bisect
call (45 inner iters) costs ~5s; cc_coupled_bisect is the same order.
G0's outer shooting loop uses OUTER_ITERS=30 bisections on e31 (bracket
width 7.0 needs ~21 halvings for 1e-6 relative on E31_TRUE=4.1; 30 is
headroom) plus 2 initial bracket evaluations -- about 32 FF coupled_
bisect calls (~160s), a few more for G1/G2/G_reflection (~25s), and the
same again for the optional C-C leg (~185s) -- roughly 6-7 minutes
total serial. Backgrounded with nohup when run interactively; SLURM
budget below is generous headroom for the real cluster.
"""
import json
import os
import sys
import time

sys.path.insert(0, os.environ.get("PKG_PATH",
                                  os.path.join(os.path.dirname(__file__), "..")))
import plate_solver as ps  # noqa: E402
from plate_solver.piezo_monolithic import PiezoMonolithicOutOfPlaneSolver  # noqa: E402
from plate_solver.workers import (  # noqa: E402
    _piezo_mono_coupled_ff_root_worker,
    _piezo_mono_coupled_cc_root_worker,
)

EXPECT_SOLVER_VERSION = os.environ.get("EXPECT_SOLVER_VERSION", "2026-07-10.s10")
DPS = int(os.environ.get("PIEZO_DPS", "60"))
INNER_ITERS = int(os.environ.get("PIEZO_INNER_ITERS", "45"))
OUTER_ITERS = int(os.environ.get("PIEZO_OUTER_ITERS", "30"))
RUN_CC = os.environ.get("PIEZO_RUN_CC", "1") != "0"
G0_TOL_REL = 1e-6
WORKER_TOL_REL = 1e-9

# Duan Table 1 / Paper 4 BASE_KWARGS (LESSONS_LEARNED.md Sec 18.200),
# Duan radii (Sec 18.201), full ceramic thickness 2H = 0.02 m.
R_I, R_O, H = 0.1, 0.6, 0.01
C11E, C12E, C13E, C33E = 132e9, 71e9, 73e9, 115e9
RHO = 7500.0
E31_TRUE, E33 = 4.1, 14.1
X11, X33 = 7.124e-9, 5.841e-9

BASE_KWARGS = dict(
    r_i=R_I, r_o=R_O, H=H,
    C11E=C11E, C12E=C12E, C13E=C13E, C33E=C33E, rho=RHO,
    e33=E33, X11=X11, X33=X33, dps=DPS,
)

# Physical-branch bracket: clear of e31_bar=0 (~8.9504) and the
# reflection twin (~13.80). Do not widen past 8.9504 without re-deriving
# what happens to the cubic there (a3 -> 0, degree drops).
E31_LO, E31_HI = 1.0, 8.0
NEG_LO, NEG_HI = -8.0, -1.0
REFLECTION_TWIN = 2.0 * (C13E / C33E) * E33 - E31_TRUE

# omega search brackets (rad/s), wide enough to cover e31 in [1, 8]
# (scanned interactively this session: omega(1.0)=490.34,
# omega(4.1)=473.25 [anchor], omega(8.0)=462.83; elastic=462.398).
FF_LO, FF_HI = 400.0, 600.0
CC_LO, CC_HI = 1600.0, 1950.0


def _solver(e31, kwargs=None):
    kw = dict(kwargs if kwargs is not None else BASE_KWARGS)
    kw["e31"] = e31
    return PiezoMonolithicOutOfPlaneSolver(**kw)


def _omega_ff(e31, iters=INNER_ITERS):
    return _solver(e31).coupled_bisect(FF_LO, FF_HI, 0, iters=iters)


def _omega_cc(e31, iters=INNER_ITERS):
    return _solver(e31).cc_coupled_bisect(CC_LO, CC_HI, 0, iters=iters)


def _invert_e31(fwd, omega_target, lo_p, hi_p, iters_outer=OUTER_ITERS):
    g_lo = fwd(lo_p) - omega_target
    g_hi = fwd(hi_p) - omega_target
    sign_flip = (g_lo > 0) != (g_hi > 0)
    lo, hi, glo = lo_p, hi_p, g_lo
    for _ in range(iters_outer):
        mid = 0.5 * (lo + hi)
        gm = fwd(mid) - omega_target
        if (gm > 0) == (glo > 0):
            lo, glo = mid, gm
        else:
            hi = mid
    return 0.5 * (lo + hi), sign_flip, g_lo, g_hi


def _run_leg(name, fwd, om_lo, om_hi, worker_fn, det_zero_fn, note):
    """One BC leg (F-F or C-C): worker gate, G0, G1, G2, G_reflection."""
    results = {}

    # --- G_worker: scalar-reconstruction regression gate ---
    t0 = time.time()
    om_inprocess = fwd(E31_TRUE)
    worker_args = (R_I, R_O, H, C11E, C12E, C13E, C33E, RHO,
                   E31_TRUE, E33, X11, X33, DPS, 0, om_lo, om_hi, INNER_ITERS)
    om_worker = worker_fn(worker_args)
    worker_rel = abs(om_worker - om_inprocess) / om_inprocess
    g_worker_pass = worker_rel < WORKER_TOL_REL
    note("%s G_worker: in_process=%.10f worker=%.10f rel=%.3e pass=%s (%.1fs)"
         % (name, om_inprocess, om_worker, worker_rel, g_worker_pass,
            time.time() - t0))
    results["g_worker_pass"] = g_worker_pass
    results["omega_true_inprocess"] = om_inprocess
    results["omega_true_worker"] = om_worker

    omega_target = om_inprocess  # nature's exact SC frequency, no noise

    # --- G0: inverse round trip on the physical branch ---
    t0 = time.time()
    e31_hat, sign_flip, g_lo, g_hi = _invert_e31(
        fwd, omega_target, E31_LO, E31_HI)
    g0_rel = abs(e31_hat - E31_TRUE) / E31_TRUE
    g0_pass = sign_flip and (g0_rel < G0_TOL_REL)
    note("%s G0: e31_hat=%.10g e31_true=%s rel_err=%.3e sign_flip=%s "
         "pass=%s (%.1fs)"
         % (name, e31_hat, E31_TRUE, g0_rel, sign_flip, g0_pass,
            time.time() - t0))
    results.update(e31_hat=e31_hat, g0_rel=g0_rel, g0_sign_flip=sign_flip,
                    g0_pass=g0_pass)

    # --- G1: negative controls ---
    t0 = time.time()
    gneg_lo = fwd(NEG_LO) - omega_target
    gneg_hi = fwd(NEG_HI) - omega_target
    neg_sign_flip = (gneg_lo > 0) != (gneg_hi > 0)
    neg_control_pass = not neg_sign_flip  # must NOT bracket a root
    om_wrong_sign = fwd(-E31_TRUE)
    wrong_sign_far = abs(om_wrong_sign - omega_target) / omega_target > 0.05
    try:
        # e31=0.0 does not raise at construction time -- _require_
        # coupled_consts is only invoked inside coupled_det/coupled_bisect
        # (and the C-C siblings), so the genuine singular-limit check
        # (PAPER5_DERIVATION.md Sec 2) must be exercised through a real
        # det call, not just __init__.
        det_zero_fn(_solver(0.0))
        e31_zero_raises = False
    except ValueError:
        e31_zero_raises = True
    g1_pass = sign_flip and neg_control_pass and wrong_sign_far and e31_zero_raises
    note("%s G1: neg_bracket_sign_flip=%s (want False) wrong_sign_omega=%.6f "
         "vs target=%.6f (far=%s) e31=0_raises=%s pass=%s (%.1fs)"
         % (name, neg_sign_flip, om_wrong_sign, omega_target, wrong_sign_far,
            e31_zero_raises, g1_pass, time.time() - t0))
    results.update(g1_neg_bracket_sign_flip=neg_sign_flip,
                   g1_wrong_sign_omega=om_wrong_sign,
                   g1_wrong_sign_far=wrong_sign_far,
                   g1_e31_zero_raises=e31_zero_raises,
                   g1_pass=g1_pass)

    # --- G2: sensitivity + propagated uncertainty (reported, not gated) ---
    t0 = time.time()
    dp = 0.01 * E31_TRUE
    om_plus = fwd(E31_TRUE + dp)
    om_minus = fwd(E31_TRUE - dp)
    domega_de31 = (om_plus - om_minus) / (2 * dp)
    note("%s G2 forward FD: domega/de31=%.6e rad/s per C/m^2 (%.1fs)"
         % (name, domega_de31, time.time() - t0))
    propagated = {}
    for rel_prec in (1e-4, 1e-3):
        d_om = rel_prec * omega_target
        dp_prop = d_om / abs(domega_de31)
        rel_u = dp_prop / abs(E31_TRUE)
        propagated["%g" % rel_prec] = dict(
            assumed_omega_rel_precision=rel_prec,
            propagated_de31=dp_prop,
            propagated_de31_rel=rel_u,
        )
        note("%s G2 propagated: %.4f%% freq -> de31=%.6g (%.4f%% of e31_true)"
             % (name, rel_prec * 100, dp_prop, rel_u * 100))
    results.update(g2_domega_de31=domega_de31, g2_propagated=propagated)

    # --- G_reflection: bonus structural check (reported, not gated) ---
    t0 = time.time()
    om_twin = fwd(REFLECTION_TWIN)
    refl_rel = abs(om_twin - omega_target) / omega_target
    note("%s G_reflection: twin=%.10f omega(twin)=%.10f vs true=%.10f "
         "rel=%.3e (%.1fs)"
         % (name, REFLECTION_TWIN, om_twin, omega_target, refl_rel,
            time.time() - t0))
    results.update(reflection_twin=REFLECTION_TWIN, omega_at_twin=om_twin,
                   reflection_rel=refl_rel)

    results["leg_pass"] = g_worker_pass and g0_pass and g1_pass
    return results


def main():
    t_all = time.time()
    print("job start: dps=%s inner_iters=%s outer_iters=%s run_cc=%s"
          % (DPS, INNER_ITERS, OUTER_ITERS, RUN_CC), flush=True)
    if ps.SOLVER_VERSION != EXPECT_SOLVER_VERSION:
        print("PREFLIGHT FAIL: SOLVER_VERSION=%r != %r"
              % (ps.SOLVER_VERSION, EXPECT_SOLVER_VERSION), flush=True)
        sys.exit(2)
    print("preflight OK: SOLVER_VERSION=%s" % ps.SOLVER_VERSION, flush=True)
    if not hasattr(PiezoMonolithicOutOfPlaneSolver, "coupled_bisect"):
        print("PREFLIGHT FAIL: deployed PiezoMonolithicOutOfPlaneSolver "
              "has no coupled_bisect. Push plate_solver/piezo_monolithic.py "
              "AND plate_solver/workers.py before re-running.", flush=True)
        sys.exit(2)
    print("preflight OK: coupled_bisect present", flush=True)

    log = []

    def note(msg):
        log.append(msg)
        print(msg, flush=True)

    note("REFLECTION_TWIN(e31=%.4f) = %.10f  (2*(C13E/C33E)*e33 - e31)"
         % (E31_TRUE, REFLECTION_TWIN))

    ff = _run_leg("FF", _omega_ff, FF_LO, FF_HI,
                  _piezo_mono_coupled_ff_root_worker,
                  lambda s: s.coupled_det(FF_LO, 0), note)

    all_results = {"ff": ff}
    all_pass = ff["leg_pass"]

    if RUN_CC:
        cc = _run_leg("CC", _omega_cc, CC_LO, CC_HI,
                      _piezo_mono_coupled_cc_root_worker,
                      lambda s: s.cc_coupled_det(CC_LO, 0), note)
        all_results["cc"] = cc
        all_pass = all_pass and cc["leg_pass"]
    else:
        note("CC leg skipped (PIEZO_RUN_CC=0)")

    all_results["elapsed_s"] = time.time() - t_all
    all_results["log"] = log

    out_path = os.path.join(os.path.dirname(__file__) or ".",
                             "piezo_p5_e31_inverse_results.json")
    with open(out_path, "w") as f:
        json.dump(all_results, f, indent=2)

    print("--- summary ---", flush=True)
    print("  FF: g_worker=%s g0_rel=%.3e g1=%s g2@0.01%%=%.4f%% g2@0.1%%=%.4f%%"
          % (ff["g_worker_pass"], ff["g0_rel"], ff["g1_pass"],
             ff["g2_propagated"]["0.0001"]["propagated_de31_rel"] * 100,
             ff["g2_propagated"]["0.001"]["propagated_de31_rel"] * 100),
          flush=True)
    if RUN_CC:
        cc = all_results["cc"]
        print("  CC: g_worker=%s g0_rel=%.3e g1=%s g2@0.01%%=%.4f%% g2@0.1%%=%.4f%%"
              % (cc["g_worker_pass"], cc["g0_rel"], cc["g1_pass"],
                 cc["g2_propagated"]["0.0001"]["propagated_de31_rel"] * 100,
                 cc["g2_propagated"]["0.001"]["propagated_de31_rel"] * 100),
              flush=True)
    print("SENTINEL " + ("PASS_ALL" if all_pass else "FAIL_ALL")
          + " all_pass=%s (%.1fs total)" % (all_pass, time.time() - t_all),
          flush=True)


if __name__ == "__main__":
    main()
