#!/bin/bash
#SBATCH --job-name=geomsweep_ip_r200
#SBATCH --output=geomsweep_ip_r200_%j.out
#SBATCH --error=geomsweep_ip_r200_%j.err
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --time=00:30:00
#SBATCH --partition=general

# Generated by generate_geomsweep_ansys_decks.py -- 6 angle passes, single
# mesh (NDIV=64), one geometry-sweep radius ratio. See that script's
# docstring for the geometry-mapping derivation and the single-mesh
# scope trade-off.
# NOTE: no explicit `cd` here on purpose (matches this project's Ansys
# submit-script convention) -- submit from the SAME directory as
# ansys_geomsweep_ip_r200.inp (cd there, then `sbatch submit_ansys_geomsweep_ip_r200.sh`).
module load ansys/2024R2 2>/dev/null || module load ansys 2>/dev/null

echo "Job $SLURM_JOB_ID on $(hostname)"
echo "Start: $(date)"

mapdl -b -smp -np ${SLURM_CPUS_PER_TASK:-8} -i ansys_geomsweep_ip_r200.inp -o ansys_geomsweep_ip_r200_out.txt

echo "End: $(date)"
for f in geomsweep_*_ip_*.txt; do
  echo "--- $f ---"; cat "$f" 2>/dev/null; echo
done
